name = "kammerlo/orcfax-test"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'kammerlo/orcfax-test'"

[repository]
user = "kammerlo"
project = "orcfax-test"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "orcfax/orcfax-aiken"
version = "f9c0241f6705098d8492154be792fbd62f1a96c5"
source = "github"

[config]
